### ISSUE TITLE
Invalid URL [-0]

### ISSUE THREAD

**Issue by skodapetr** [bugulin/ndbi046#2]
Ve výstupu je třeba:
```
<dataset/population2021/obs-00000> a qb:Observation ;
```
Což není myslím, validní URL. Ideálně by mělo začínat https://

**Comment by bugulin** [comment]
Validní _absolutní_ URL to sice není, ale stále je to validní [identifikátor v Turtle](https://www.w3.org/TR/turtle/#sec-iri). Pro přehlednost používám relativní IRI, přičemž _base IRI_ je explicitně nastavena na `https://bugulin.github.io/ndbi046/resource/` (pomocí `@base` direktivy, která by měla být hned na prvním řádku výstupu).

Pokud potřebujete (všude) vidět absolutní identifikátory, zkusil bych např. formát N-Triples (`--format=nt`).

**Comment by skodapetr** [comment]
Máte pravdu, přehlédl jsem ten base. Děkuji za upozornění.
